### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by pbsch** [adrian-bl-yuga/device-sony-c6603#13]
I want to report a bug related to the camera, sometimes when I open the app I get a stretched image, I have to close and open again the camera app to solve it, sometimes I have to do it several times to get the camera working correctly.

**Comment by adrian-bl-yuga** [comment]
Please post a logcat and the output of 'cat /proc/version'

**Comment by pbsch** [comment]
output of 'cat /proc/version'
Linux version 3.4.104-perf-g1fe90cf (adrian@fuzzy)
(gcc version 4.8 (GCC)) #1 SMP PREEMPT Sun Nov 16
16:40:22 CET 2014

 Is this one enough?  http://pastebin.com/zE0nXTtV

**Comment by adrian-bl-yuga** [comment]
Hmm: How often do you see this issue?
I only was able to reproduce this exactly ONCE this morning (and i've never seen it before).

Are you switching between multiple camera apps or are you only using the stock camera?

**Comment by ostrand** [comment]
I also have the same issue... happens every time i start the camera. If i switch to another resolution, the preview is fine. This happens no matter what the resolution the camera is set tp... The photo itself is good. 
I flashed 5.0.3 over 5.0.1 without clearing userdata (only system and boot)

i'm running 5.0.3

**Comment by pbsch** [comment]
Lately almost every time I open the camera app, I only use stock camera.

**Comment by pbsch** [comment]
So just to let you know the bug is not present when I set the size to 8.6 MP or a smaller size.

**Comment by ostrand** [comment]
it is for me - but only the first time after i change the resolution. 
If i close and start the camera again, the preview is still stretched. (with resolution set to 16:9 - 8,6 mpx)
If i then change the resolution to something else and go back to the preview, it is fine.
Then i exit the camera and swipe it away from the "recent applications" and start it again, then preview is stretched.

**Comment by ostrand** [comment]
Resolved in 5.0.4 as far as I can see

**Comment by pbsch** [comment]
Yes it didn't happen again with the latest build

**Comment by adrian-bl-yuga** [comment]
I still see it in 5.0.4 (btw: @ostrand thanks for the instructions on how to reproduce the issue!) - but this is IMO a very minor issue as it only affects the stock camera (and does not have any impact on the actual photos).

I'll have a look at this - some day ;-) (volunteers are welcome!)

**Comment by adrian-bl-yuga** [comment]
closing this as i could not reproduce it in the latest builds (probably still there - but a very minor issue)
